"""delete_key

Revision ID: 5d9f32a937e1
Revises: 28614a7e257c
Create Date: 2025-04-28 23:21:25.444262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d9f32a937e1'
down_revision: Union[str, None] = '28614a7e257c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('warehouse_product_name_fkey', 'warehouse', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('warehouse_product_name_fkey', 'warehouse', 'product', ['product_name'], ['name'])
    # ### end Alembic commands ###
