"""refactor_model

Revision ID: 28614a7e257c
Revises: 18202db18ebd
Create Date: 2025-04-27 19:32:43.273104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28614a7e257c'
down_revision: Union[str, None] = '18202db18ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.alter_column('clients', 'fio',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'clients', ['fio'])
    op.add_column('orders', sa.Column('client_fio', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('product_name', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('address', sa.String(), nullable=True))
    op.drop_constraint('orders_product_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_client_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'product', ['product_name'], ['name'])
    op.create_foreign_key(None, 'orders', 'clients', ['client_fio'], ['fio'])
    op.drop_column('orders', 'client_id')
    op.drop_column('orders', 'product_id')
    op.add_column('warehouse', sa.Column('product_name', sa.String(), nullable=False))
    op.drop_constraint('warehouse_product_id_fkey', 'warehouse', type_='foreignkey')
    op.create_foreign_key(None, 'warehouse', 'product', ['product_name'], ['name'])
    op.drop_column('warehouse', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'warehouse', type_='foreignkey')
    op.create_foreign_key('warehouse_product_id_fkey', 'warehouse', 'product', ['product_id'], ['id'])
    op.drop_column('warehouse', 'product_name')
    op.add_column('orders', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_client_id_fkey', 'orders', 'clients', ['client_id'], ['id'])
    op.create_foreign_key('orders_product_id_fkey', 'orders', 'product', ['product_id'], ['id'])
    op.drop_column('orders', 'address')
    op.drop_column('orders', 'product_name')
    op.drop_column('orders', 'client_fio')
    op.drop_constraint(None, 'clients', type_='unique')
    op.alter_column('clients', 'fio',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('clients', 'is_superuser')
    # ### end Alembic commands ###
